# These functions are to check the check properties of report_data_list objects
# generated by calls to create_reports()

check_active_lcs <- function(report_data_list, items){
  # check that all learning conditions found to be "active" match those marked
  # in copilot_items.csv in the `driver` column
  
  # create a table of all the "active" values of ls_out corresponding to
  # the "label" values
  lcs <- report_data_list %>% 
    lapply(., function(x) return(x$learning_conditions))
  
  create_lc_df <- function(lc){
    lc_df <- data.frame(
      label = lc %>% lapply(., function(x) return(x$label)) %>% unlist,
      active = lc %>% lapply(., function(x) return(x$active)) %>% unlist
    ) 
  }
  
  # create a data.frame showing the labels and active markers for each lc
  # for each reporting unit
  lc_df <- lapply(lcs, create_lc_df) %>%
    util.rbind_union() %>%
    mutate(ru = gsub("\\.[1-9]+", "", row.names(.)))
  
  actual_active_lcs <- lc_df %>%
    dplyr::filter(active) %>%
    dplyr::pull(label) %>%
    unique
  
  # @to-do: this is not finished, there's some weirdness with dashes vs underscores
  expected_active_lcs <- items %>%
    dplyr::filter(!util.is_blank(driver)) %>%
    dplyr::pull(driver) %>%
    unique
  
  actual_not_expected <- actual_active_lcs[!actual_active_lcs %in% expected_active_lcs]
}

check_rus <- function(report_data_list, expected_rus){
  # check that the names of the elements in report_data_list match
  # the expected reporting units (expected_rus)
  present_rus <- names(report_data_list)
  missing_rus <- present_rus[!present_rus %in% expected_rus]
  
  if(length(missing_rus) > 0){
    stop("Stopping script. report_data_list object is missing the " %+%
           "following reporting units: " %+%
           paste0(missing_rus, ", "))
  }
}

check_present_bar_graphs <- function(report_data_list){
  # check that bar graphs are present where the participation table lists
  # more than five participating students for the most recent cycle.
  # note that this is hard right now because the participation_data_table
  # is printed, human-readable character strings only. But seems like
  # create_reports() could return the raw data too
}

check_present_change_graphs <- function(report_data_list){
  # check that change graphs are present where the participation table lists
  # more than five participating students for the most recent cycle.
  # note that this is hard right now because the participation_data_table
  # is printed, human-readable character strings only. But seems like
  # create_reports() could return the raw data too
}

check_participation <- function(report_data_list, triton_tbl){
  # check how the numbers in participation_table_df match what's expected
  # from the database. I'm not sure what the expected behavior is here 
}

# is there some way to check ag_metrics_small to make sure the participation
# breakdown by subset_feature is correct?